services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_qchN41BlUWiG@ep-little-bar-anadxcwr-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=presupuesto_jwt_secret_2024_seguro
      - JWT_EXPIRES_IN=7d
      - PORT=3000
    working_dir: /app/apps/backend

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    working_dir: /app/apps/frontend